### ISSUE TITLE
Error with Emboss identifiers

### ISSUE THREAD

**Issue by jirivorel** [sestaton/HMMER2GO#7] opened 2016-03-01 09:48 UTC
Hi Evan,
I wanna use Hmmer2go - it's great tool for my purpose, but after run this simple command ... 

$ hmmer2go getorf -i Data/nk_seq -o prot_seq_trans -l 90 

I get an error message ... 

ERROR: Identifiers such as 'Locus_1_Transcript_1/1_Confidence_1.000_Length_826' will produce unexpected renaming with EMBOSS. Exiting. at /usr/local/share/perl/5.18.2/HMMER2GO/Command/getorf.pm line 161, <$fh> chunk 2.

I am not familiar with Emboss, so i am not sure, what is wrong with my seq identifiers.

Thank you for your time and reply

Jirka

**Comment by sestaton** [comment] 2016-03-01 18:18
The issue is the slash in the FASTA header, which will cause EMBOSS to do reformat your IDs or just halt. You can fix your DNA sequences with this script: [clean_multifasta.pl](https://github.com/sestaton/sesbio/blob/master/gene_annotation/clean_multifasta.pl). That should solve the problem for you. 

Let me know if you have any other questions or issues.

**Comment by jirivorel** [comment] 2016-03-01 22:43
Many thanks for the prompt reply now is it ok without error message. But still I've some problems ...

- Simple command (only with input and output files specifications) works well ... result is file with the longest ORFs in aminoacids. Translation regions are between STOP codons.
  $ hmmer2go getorf -i nucl_seq_input.fasta -o prot_seq_output.fasta

- But if I want same coding sequences in nucleics (not in aminoacids) I uses following script (input file is same like in previous case), I get ORFs in aminoacids again. Translation regions are between START and STOP codons.
  $ hmmer2go getorf -i nucl_seq_input.fasta -o nucl_seq_ORFs.fasta -t 2

- And the last one, when I want specify minimum length of ORFs to report on different value than default, I get many aminoacids ORFs in output file for each single nucl. seq., not only the longest one (I'm not interest to find all the ORFs).
  $ hmmer2go getorf -i nucl_seq_input.fasta -o prot_seq_minlen_100.fasta -l 100

This is a couple of problems that prevents me get the coding sequence of amino acids and nucleotides equivalent.

**Comment by sestaton** [comment] 2016-03-02 02:06
Thanks for the report. The first issue is fixed on the master branch, and I'm looking into the second issue.

**Comment by sestaton** [comment] 2016-03-02 02:12
Okay, I have looked at the tests and I'll need to see an example to help with the last issue you mention. In the output I get, I am seeing only the longest ORF for each input sequence. For a multi-FASTA file, that still means there will be many output sequences, specifically, there will be one for every input sequence as long as it passes the thresholds.

**Comment by jirivorel** [comment] 2016-03-02 10:43
OK, here is a short fasta file with 21 nucl. sequences (https://github.com/sestaton/HMMER2GO/files/154531/nucl_seq_input.fasta.zip)
I used single FASTA file as an input. After writting this command:

`hmmer2go getorf -i nucl_seq_input.fasta -o prot_seq_minlen_100.fasta -l 100`

I get FASTA output in aminoacids with 1214 sequnces - this ...
(https://github.com/sestaton/HMMER2GO/files/154539/prot_seq_minlen_100.fasta.zip)

**Comment by sestaton** [comment] 2016-03-02 12:52
You might want to check which EMBOSS version you are using, that is likely the difference. I am using EMBOSS:6.5.7.0`. With this version, I am getting 725 sequences when reporting all ORFs, and 22 sequences when reporting only the longest using the command you showed. There are 22 sequences reported and not 21 because there are 2 ORFs the same length and I don't want to choose one over the other since it may influence the results. I will add a warning when this case is encountered.

**Comment by jirivorel** [comment] 2016-03-02 13:09
OK, I used version 6.6.0.0. I'll contact your server administrator with request for this older version and I'll try do it again and inform you.

**Comment by sestaton** [comment] 2016-03-02 13:18
That is interesting, can you show the output of the command `getorf -version` to be clear. To my knowledge, version 6.5.7 is the latest and I'm not sure where version 6.6.0.0 can be found. It is not on the FTP servers.

**Comment by jirivorel** [comment] 2016-03-02 13:42
Yes, I know EMBOSS download page (where version 6.5.7. can be download, it is true), but after writing `getorf -version` and `embossversion` I get that version is: EMBOSS:6.6.0.0. Version of HMMER is 3.1b2.

**Comment by sestaton** [comment] 2016-03-02 19:30
Aside from the version question, can you confirm you only ran this command:

    hmmer2go getorf -i nucl_seq_input.fasta -o prot_seq_minlen_100.fasta -l 100

When I run that I get 22 sequences. This command will tell you the hmmer2go version: `hmmer2go --version`.

**Comment by jirivorel** [comment] 2016-03-02 20:40
Yes, I ran this command in the same form and I get 1214 protein sequences. My hmmer2go version is 0.17.1.

**Comment by sestaton** [comment] 2016-03-02 23:20
Can you show the output of this command:

    grep -c ">" nucl_seq_input.fasta; hmmer2go getorf -i nucl_seq_input.fasta -o prot_seq_minlen_100.fasta -l 100; grep -c ">" prot_seq_minlen_100.fasta

Also, I would recommend updating to the latest version to fix the first issue you mentioned about reporting the ORF type.

**Comment by jirivorel** [comment] 2016-03-03 07:41
Output is:
21
1214

**Comment by sestaton** [comment] 2016-03-03 07:46
What operating system are you using (and version)? I wouldn't think that the EMBOSS version would influence this, and unfortunately it is hard to test without knowing where to find that version. 

My only suggestion is to try the latest hmmer2go version, and once I know your OS I can try it on a cloud instance with the same set up.

**Comment by jirivorel** [comment] 2016-03-03 08:02
I am using Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-32-generic x86_64). But it is our server for computational biology, now I am waiting until our administrator makes my requirements about software - the latest hmmer2go version a EMBOSS 6.5.7 version.

**Comment by jirivorel** [comment] 2016-03-03 10:09
So, we upgrade hmmer2go on version 0.17.2 and now it's working right - somehow. I can get right count of ORFs in proteins and nucleotides too. So thank you for your time and patience.

**Comment by sestaton** [comment] 2016-03-03 15:40
That is good to hear. I'll close this issue, but don't hesitate to raise other issues if you have any questions. Thanks.

**Closed by sestaton** 2016-03-03 15:40 UTC

**Comment by abbyhudak** [comment] 2018-03-26 17:01
Hi,
I don't believe the makefile.pl worked for my sequences.  I ran the code from lines 55-184.  I'm sorry if this wasn't right, I am very new to this environment.  My sequence headers do not have slashes by they do have spaces: TRINITY_DN3_c0_g1_i1 len=205 path=[365:0-204] [-1, 365, -2]

Thanks for your help

**Comment by sestaton** [comment] 2018-03-26 18:51
Hi @abbyhudak,

I'm unclear on what command you have run. The `Makefile.PL` script just sets up the package to be tested and installed. It does not run any analysis. 

If you are having issues with the `hmmer2go getorf` command, you may want to try the [clean_multifasta.pl](https://github.com/sestaton/sesbio/blob/master/gene_annotation/clean_multifasta.pl) script listed above in this discussion. Please try that to convert your sequences to a usable format by EMBOSS. 

You will also need to build/install the package to use the programs, and it is unclear to me if that was done correctly. Let me know if you have issues with above suggestions.

Thanks.

**Comment by abbyhudak** [comment] 2018-03-26 19:35
Sorry, I did not mean to say Makefile.pl I meant clean_multifasta.pl.  I tried using the clean_multifasta.pl script but I may not have used it correctly.  Will this script get rid of spaces and brackets since EMBOSS seems to not like these?

**Comment by sestaton** [comment] 2018-03-26 20:41
Hi @abbyhudak,

The script should work fine based on the identifier you posted. If you have a file of sequences named "trinity.fas" then you can use the script like so:

    perl clean_multifasta.pl -i trinity.fas -o trinity_clean.fas

The file of transformed IDs will be in "trinity_clean.fas" which is the argument to "-o" above, the output file.

**Comment by abbyhudak** [comment] 2018-03-27 15:55
Whenever I add the script it quits and shuts out of my command prompt

**Comment by sestaton** [comment] 2018-03-27 16:29
Hi @abbyhudak, 

I'm not sure what to make of your comment without more information. Please show the command and the output of the program (it should print results to the terminal). Did check the output file?

**Comment by abbyhudak** [comment] 2018-03-27 16:33
Thanks for your quick reply with these comments

I cannot show the command or output because it shuts me out of my command prompt (the entire screen disappears and I am logged out)

**Comment by sestaton** [comment] 2018-03-27 16:45
Hi @abbyhudak,

What you describe is unrelated to HMMER2GO or this thread, but I don't mind trying to help. Please send me an email and we can continue the discussion that way. If there is something related to the original issue in this thread we can pick up the discussion here.

Thanks,
Evan

**Comment by sestaton** [comment] 2018-03-28 00:27
Hi @abbyhudak,

You can email me at: evan@evanstaton.com. The question now is about running a script and it would be better to resolve that offline so others are not getting notifications for each message and so we can keep the discussion here focused on a specific issue.

Thanks,
Evan

**Comment by abbyhudak** [comment] 2018-03-29 23:40
Great, thanks!

Abby

________________________________

**Comment by abbyhudak** [comment] 2018-05-21 19:56
My command:
./clean_multifasta.pl -i Mpotamo.fasta -o Mpotamo_clean.fasta

My error:
./clean_multifasta.pl: line 7: syntax error near unexpected token `newline'
./clean_multifasta.pl: line 7: `<!DOCTYPE html>'

**Comment by sestaton** [comment] 2018-05-24 16:15
Hi @abbyhudak,

Could you create a separate issue for this topic at: https://github.com/sestaton/sesbio/issues

I'd like to keep this message board for the hmmer2go issues. Also, please show a bit of the file for testing. That message suggests there is likely something unexpected with the input.

Thanks.
