### ISSUE TITLE
Issue with getorf command

### ISSUE THREAD

**Issue by LorenaDerezanin** [sestaton/HMMER2GO#15] opened 2018-05-02 20:20 UTC
Hi Evan,

I have some issues with the newest version of hmmer2go (HMMER2GO-0.17.7)
 
I've just run a test run on a small fasta file containing a unitig (short nuclear sequence used in building of contigs during the genome assembly).

```bash
hmmer2go getorf -i AIRE_splitted_UTG_reads_ab_clean.fasta -o hmmer2go_test_AIRE_ab_fasta --verbose -n 8 
```
It throws the following error, although it produces an output file with a detected ORF.

```
========== Searching for ORFs with minimum length of 80.
Can't use string ("1") as a SCALAR ref while "strict refs" in use at /home/lorke/perl5/lib/perl5/HMMER2GO/Command/getorf.pm line 112.
```

This is the content of the input file:
```
>utg7180000171672
CTTCCCAGTATAGGAACTGATGAGGCTTCAGAACAAGTGGGTGCCCACTCTAGCCAAGGT
GTAGTGAAAACCCCATCCCCTACGTGCAGGCTCCCTGGTGAGCAGGCAGTGTAGCTTGGG
GTAGCTCTCCATGTTGTAGTCCTTGGTAAGACTGCTCCAGAAGGCCCGGAGGATGGGTCG
ACCCTGAAGCAGGACCCAGGACACCAGGGAGTACATGGCCCTGTGCACCCCGGCCTTCCC
CTGGCTCACCATCGTGTCCTGAGAGACGTAGACAGCAGAGAGCTCTCCTCAAGCGTCGTT
TTCATGATGATGCATTCAACAGTGGTACAAATATTTAATTATTTTGTCAAGTATTTAGAG
TGTTGCCCGTGGATTGATAGATGGATATTTTATTCATCCCCTTGGGGAACTCAGGTTTCC
AGTAGCTCACAAAGGTAGTCGACAGATGGTAACGAAATGGACAACCGGTAAAAGTCAATC
AAAAAAGTAAATAAAAGTGAGCAATATTGCACACAATTGAAATTGCATTTAAAAAACAGC
CAGTGGTAGACATAAATAAATAAATATTACGCAATTCCACACTGTCCAGTGTGTGTGGGG
GCTGGGTTGAGGGAGAGAGAGACAGAAAGAGTCATGATGGGCCACTACCCTTGCCTGAGT
TGTTGTGTAGTCTGATGGCTGTGGGGACAAAGGTTGTTCTGTACTGTACAGGTACAGAAC
ATGAAGATGTACACAACCTATTATTGCTTGTATAATATCCCATCAAACAATGACCTTCAC
AAGAGCACACTGGCAACTAAACGTAAACACAGGTGCTTATGATATCAATCCTTGACTGAC
ATAGTTTCAAATTGGATTCGTTTTACTATTAAGGTCAAATGATGATCTGATTATAGCATG
TCAAATAAATGAAAATATTGTATTGCAACCAAAAGGTTGTAGCATGACCGTCGACGCTAC
GTTAGCCTCTTCTGGTCGGTGTTGTGTGATGGATGAGCTCCTATCCTCTTACCTTGAGCA
GCTGGTCAGTGATGATGTTTCTATCAGCCAGGCCGTGCACCAGGGGGAAGGGGTCGTCTA
CGGCCATGGCGATGTCGGTGCGCAGCTCTCTCAGCCGAGTGCGAAGGTCGGTGGTCCCAT
AAATCTCAACCCTGGACATGTTACTCTAACTCTGTGTGTAGATATCTGAGTCCCCGTAAA
TCTGAAGCATGAACATGTTACCCTGAGTCTTTTTTCGGTGTATGCAGGTCTGTTGGTGCA
TCCATACACTAAGCCTGATGGACGTTTAGTGTTGTGTGGACAAGAAGAACGGGGATCCTG
GTTTTGATGAGTTGGACGTGTCCACCCTTTTACACCCTGAACGTGTGAGGGAGTAACAGG
GAGGTTTGAGATGTGTCAATGTTGCCTGTGAGGAGGTGTGTCTTTTTATAAAAGGAAGGT
GGTGTTTTAGAGAAAAGAGTCAAATATCTGAAATAGTTTGCATCCATCTAGTCGAGTCTT
TGGAATTGCATGCGATCAAGTGTTATAAATGCGCACACAAAGACATACACACACACACAC
ACCCATACACACAGACACAATTCCCTTAACATTTCAGGCTATTAAAACATCGATAGGAAT
AAAAAGTAATATTTT
```

I've installed the older version of hmmer2go (HMMER2GO-0.17.2)
and run the same test:

```bash
hmmer2go getorf -i AIRE_splitted_UTG_reads_ab_clean.fasta -o hmmer2go_older_version_AIRE_ab_fasta --verbose -n 8
```

```
========== Searching for ORFs with minimum length of 80.

========== 1 and 1 sequences in AIRE_splitted_UTG_reads_ab_clean.fasta.

========== 1 sequences processed with ORFs above 80.

========== 1.00 percent of sequences contain ORFs above 80.
```

				
and it went without any issues. I've checked both output files with diff and they're identical.

I've repeated the test run on additional fasta files with the older version of hmmer2go and it also went smoothly.
It seems to me that the bug might have been introduced in the latest version.

All the best,

Lorena

**Comment by sestaton** [comment] 2018-05-25 21:21
Thanks again for the report. This was just a warning BTW and would not have any effect on the results. It was caused by a change that was not handled correctly.

This is fixed in the master branch and in the latest release (v0.17.8).

**Closed by sestaton** 2018-05-25 21:21 UTC
